default: &default
  locastyle:
    css:   "http://assets.locaweb.com.br/locastyle/3.2.2/stylesheets/locastyle.css"
    js:    "http://assets.locaweb.com.br/locastyle/3.2.2/javascripts/locastyle.js"

  site:
    name: Locateca
    title: Locateca - Gerenciamento de Biblioteca
    domain: biblioteca.locaweb.com.br
    url: http://biblioteca.locaweb.com.br
    email: biblioteca@locaweb.com.br

development: &development
  <<: *default
  secret_key_base: 1abf63af319db398a91e31fd5982a165edd0b917bcce593fea3e5a450d587957be6451df8845e15847fbdc98bc91e6e4c968aa8df492c2533477ddc0aa584791

test:
  <<: *default
  secret_key_base: 64a805f44e0baf4c2725d07c13225717559afe6205340b3dc95cc71af66a9ec5e9ff3269be031f6066fa51ac22f90bfa96c0722b4b7662303841af0d384bfeaa

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
