# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1abf63af319db398a91e31fd5982a165edd0b917bcce593fea3e5a450d587957be6451df8845e15847fbdc98bc91e6e4c968aa8df492c2533477ddc0aa584791

test:
  secret_key_base: 64a805f44e0baf4c2725d07c13225717559afe6205340b3dc95cc71af66a9ec5e9ff3269be031f6066fa51ac22f90bfa96c0722b4b7662303841af0d384bfeaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
